shader_type spatial;

void vertex() {
	if (VERTEX == vec3(0,0,1))
	{
		
	}
	else if (VERTEX == vec3(0,1,1))
	{
		
	}
	else if (VERTEX == vec3(1,0,1))
	{
		
	}
}

void fragment() {
	// Called for every pixel the material is visible on.
}

//void light() {
	// Called for every pixel for every light affecting the material.
	// Uncomment to replace the default light processing function with this one.
//}
