#[compute]
#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D color_texture;
layout(set = 0, binding = 1) uniform sampler2D depth_texture;
layout(set = 0, binding = 2, r32f) readonly uniform image2D linear_depth_texture;

layout(set = 0, binding = 3, std430) buffer restrict readonly AtmosphereData {
    float scale;
    float density_falloff;
    uint light_sampling_count;
    uint optical_depth_sampling_count;
    vec4 scattering_coefficients;
} atmosphere_data;

layout(set = 0, binding = 4, std430) buffer restrict readonly WorldData {
    float radius;
    float height_scale;
    vec2 padding;
    mat4 planet_transform_matrix;
} world_data;

layout(push_constant, std430) uniform PushConstants {
    vec4 camera_position;
    vec4 frustum_top_left;
    vec4 frustum_top_right;
    vec4 frustum_bottom_left;
    vec4 frustum_bottom_right;
    vec4 sun_direction;
} push_constants;

#[include] res://Shaders/GLSL/ShaderIncludes/Constants.inc
#[include] res://Shaders/GLSL/ShaderIncludes/Functions.inc

bool solve_quadratic(float a, float b, float c, out float x0, out float x1) {
    float discr = b * b - 4.0 * a * c;

    if (discr < 0.0)
        return false;

    if (discr == 0.0) {
        x0 = x1 = -0.5 * b / a;
    } else {
        float q = b > 0.0
            ? -0.5 * (b + sqrt(discr))
            : -0.5 * (b - sqrt(discr));

        x0 = q / a;
        x1 = c / q;
    }

    if (x0 > x1) {
        float temp = x0;
        x0 = x1;
        x1 = temp;
    }

    return true;
}

vec2 ray_sphere_intersection(vec3 sphere_center, float sphere_radius, vec3 ray_origin, vec3 ray_direction) {
    vec3 offset = ray_origin - sphere_center;
    float a = 1;
    float b = 2 * dot(offset, ray_direction);
    float c = dot(offset, offset) - sphere_radius * sphere_radius;
    float discriminant = b * b - 4.0 * a * c;
    
    if (discriminant > 0) {
        float s = sqrt(discriminant);
        float distance_to_sphere_near = max(0, (-b - s) / (2 * a));
        float distance_to_sphere_far = (-b + s) / (2 * a);

        if (distance_to_sphere_far >= 0) {
            return vec2(distance_to_sphere_near, distance_to_sphere_far - distance_to_sphere_near);
        }
    }
    return vec2(-1, -1);
}

vec3 get_ray_direction(ivec2 pixel) {
    ivec2 texture_size = imageSize(color_texture);
    vec2 uv = (vec2(pixel) + 0.5) / vec2(texture_size);

    vec3 bottom = mix(push_constants.frustum_bottom_left.xyz, push_constants.frustum_bottom_right.xyz, uv.x);
    vec3 top = mix(push_constants.frustum_top_left.xyz, push_constants.frustum_top_right.xyz, uv.x);
    vec3 ray = mix(bottom, top, uv.y);

    return normalize(ray);
}

float get_scene_depth(ivec2 pixel) {
    float depth = imageLoad(linear_depth_texture, pixel).r;

    if (depth < 0.0)
        return 1e30;

    return depth;
}

float density_at_point(vec3 density_sample_point, vec3 planet_position) {
    float height_above_surface = length(density_sample_point - planet_position) - world_data.radius;
    float height01 = height_above_surface / (atmosphere_data.scale * world_data.radius);
    float local_density = exp(-height01 * atmosphere_data.density_falloff) * (1.0 - height01);
    return local_density;
}

float optical_depth(vec3 ray_origin, vec3 ray_direction, float ray_length, vec3 planet_position) {
    vec3 density_sample_point = ray_origin;
    float step_size = ray_length / float(atmosphere_data.optical_depth_sampling_count - 1);
    float optical_depth_value = 0.0;

    for (uint i = 0u; i < atmosphere_data.optical_depth_sampling_count; i++) {
        float local_density = density_at_point(density_sample_point, planet_position);
        optical_depth_value += local_density * step_size;
        density_sample_point += ray_direction * step_size;
    }
    return optical_depth_value;
}

float calculate_light(vec3 ray_origin, vec3 ray_direction, float ray_length, vec3 planet_position) {
    vec3 in_scatter_point = ray_origin;
    float step_size = ray_length / float(atmosphere_data.light_sampling_count - 1);
    float in_scattered_light = 0.0;

    float atmosphere_thickness = atmosphere_data.scale * world_data.radius;
    float atmosphere_radius = atmosphere_data.scale * world_data.radius + world_data.radius;

    float extinction_coefficient = 1.0 / atmosphere_thickness;

    vec3 sun_direction = (
        vec4(normalize(push_constants.sun_direction.xyz), 1.0)
        * get_rotation_from_matrix(world_data.planet_transform_matrix)
    ).xyz;

    for (uint i = 0u; i < atmosphere_data.light_sampling_count; i++) {
        float sun_ray_length = ray_sphere_intersection(planet_position, atmosphere_radius, in_scatter_point, sun_direction).y;
        float sun_ray_optical_depth = optical_depth(in_scatter_point, sun_direction, sun_ray_length, planet_position);
        float view_ray_optical_depth = optical_depth(in_scatter_point, -ray_direction,step_size * float(i), planet_position);

        float transmittance = exp(-(sun_ray_optical_depth + view_ray_optical_depth)* extinction_coefficient);
        float local_density = density_at_point(in_scatter_point, planet_position);

        in_scattered_light += local_density * transmittance * extinction_coefficient * step_size;
        in_scatter_point += ray_direction * step_size;
    }

    return in_scattered_light;
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 texture_size = imageSize(color_texture);

    if (pixel.x >= texture_size.x || pixel.y >= texture_size.y)
        return;

    vec3 planet_position = (vec4(0.0, 0.0, 0.0, 1.0) * world_data.planet_transform_matrix).xyz;
    vec3 ray_origin = push_constants.camera_position.xyz;
    vec3 ray_direction = normalize(get_ray_direction(pixel));

    float scene_depth = get_scene_depth(pixel);
    float atmosphere_radius = atmosphere_data.scale * world_data.radius + world_data.radius;


    vec2 atmosphere_hit = ray_sphere_intersection(
        planet_position,
        atmosphere_radius,
        ray_origin,
        ray_direction
    );

    float distance_to_atmosphere = atmosphere_hit.x;
    float distance_through_atmosphere = min(atmosphere_hit.y, scene_depth - distance_to_atmosphere);

    if (distance_through_atmosphere <= 0.0)
        return;

    vec3 point_in_atmosphere = ray_origin + ray_direction * distance_to_atmosphere;

    float light = calculate_light(point_in_atmosphere, ray_direction, distance_through_atmosphere, planet_position);
    vec4 original_color = imageLoad(color_texture, pixel);
    vec4 final_color = original_color * (1 - light) + light;
    imageStore(color_texture, pixel, final_color);
}

