#[compute]
#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D color_texture;
layout(set = 0, binding = 1) uniform sampler2D depth_texture;
layout(set = 0, binding = 2, r32f) readonly uniform image2D linear_depth_texture;

layout(set = 0, binding = 3, std430) buffer restrict readonly AtmosphereData {
    float radius;
    float density_falloff;
    uint light_sampling_count;
    uint optical_depth_sampling_count;
} atmosphere_data;

layout(set = 0, binding = 4, std430) buffer restrict readonly WorldData {
    float radius;
    float height_scale;
    vec2 padding;
    mat4 planet_transform_matrix;
} world_data;

layout(push_constant, std430) uniform PushConstants {
    mat4 view_projection_matrix;
    vec4 camera_position_fovy;
    vec4 sun_direction;
    vec4 near_far;
} push_constants;

vec2 ray_sphere_intersection(vec3 sphere_center, float sphere_radius, vec3 ray_origin, vec3 ray_direction) {
    vec3 offset = ray_origin - sphere_center;

    float b = dot(offset, ray_direction);
    float c = dot(offset, offset) - sphere_radius * sphere_radius;
    float h = b * b - c;

    if (h < 0.0)
        return vec2(-1.0);

    h = sqrt(h);

    float near_hit = -b - h;
    float far_hit = -b + h;

    float distance_to_sphere = max(0.0, near_hit);
    float distance_through_sphere = max(0.0, far_hit - distance_to_sphere);

    return vec2(distance_to_sphere, distance_through_sphere);
}

vec3 get_ray_direction(ivec2 pixel) {
    ivec2 texture_size = imageSize(color_texture);

    vec2 pixel_ndc = vec2(pixel + 0.5) / vec2(texture_size);
    vec2 pixel_screen = 2.0 * pixel_ndc - 1.0;

    mat4 inverse_view_projection = inverse(push_constants.view_projection_matrix);

    vec4 clip_position = vec4(pixel_screen, 1.0, 1.0);

    vec4 world_position = inverse_view_projection * clip_position;
    world_position /= world_position.w;

    return normalize(world_position.xyz - push_constants.camera_position_fovy.xyz);
}

float get_scene_depth(ivec2 pixel) {
    float depth = imageLoad(linear_depth_texture, pixel).r;

    if (depth < 0.0)
        return 1e30;

    return depth;
}

float density_at_point(vec3 density_sample_point, vec3 planet_position) {
    float height_above_surface = length(density_sample_point - planet_position) - world_data.radius;
    float height01 = height_above_surface / (atmosphere_data.radius - world_data.radius);

    float local_density = exp(-height01 * atmosphere_data.density_falloff) * (1.0 - height01);

    return local_density;
}

float optical_depth(vec3 ray_origin, vec3 ray_direction, float ray_length, vec3 planet_position) {
    vec3 density_sample_point = ray_origin;
    float step_size = ray_length / float(atmosphere_data.optical_depth_sampling_count - 1);
    float optical_depth_value = 0.0;

    for (uint i = 0u; i < atmosphere_data.optical_depth_sampling_count; i++) {
        float local_density = density_at_point(density_sample_point, planet_position);

        optical_depth_value += local_density * step_size;
        density_sample_point += ray_direction * step_size;
    }

    return optical_depth_value;
}

float calculate_light(vec3 ray_origin, vec3 ray_direction, float ray_length, vec3 planet_position) {
    vec3 in_scatter_point = ray_origin;
    float step_size = ray_length / float(atmosphere_data.light_sampling_count - 1);
    float in_scattered_light = 0.0;

    vec3 sun_direction = normalize(push_constants.sun_direction.xyz);

    for (uint i = 0u; i < atmosphere_data.light_sampling_count; i++) {
        float sun_ray_length = ray_sphere_intersection(
            planet_position,
            atmosphere_data.radius,
            in_scatter_point,
            sun_direction
        ).y;

        float sun_ray_optical_depth = optical_depth(in_scatter_point, sun_direction, sun_ray_length, planet_position);
        float view_ray_optical_depth = optical_depth(in_scatter_point, -ray_direction, step_size * float(i), planet_position);

        float transmittance = exp(-(sun_ray_optical_depth + view_ray_optical_depth));
        float local_density = density_at_point(in_scatter_point, planet_position);

        in_scattered_light += local_density * transmittance * step_size;
        in_scatter_point += ray_direction * step_size;
    }

    return in_scattered_light;
}

void main() {
    
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 texture_size = imageSize(color_texture);

    if (pixel.x >= texture_size.x || pixel.y >= texture_size.y)
        return;

    // float scene_depth = get_scene_depth(pixel);

    // if (scene_depth >= 1e29) {
    //     imageStore(color_texture, pixel, vec4(0.0, 0.0, 1.0, 1.0));
    //     return;
    // }

    // float test_depth = clamp(scene_depth / 2000.0, 0.0, 1.0);
    // imageStore(color_texture, pixel, vec4(test_depth, 0.0, 0.0, 1.0));
    // return;

    vec4 original_color = imageLoad(color_texture, pixel);
    float scene_depth = get_scene_depth(pixel);

    vec3 planet_position = (vec4(0.0, 0.0, 0.0, 1.0) * world_data.planet_transform_matrix).xyz;
    vec3 camera_position = push_constants.camera_position_fovy.xyz;
    vec3 ray_direction = get_ray_direction(pixel);
    imageStore(color_texture, pixel, vec4(ray_direction, 1));

    // vec2 atmosphere_hit = ray_sphere_intersection(
    //     planet_position,
    //     atmosphere_data.radius,
    //     camera_position,
    //     ray_direction
    // );

    // float distance_to_atmosphere = atmosphere_hit.x;
    // float distance_through_atmosphere = atmosphere_hit.y;

    // if (distance_to_atmosphere < 0.0) {
    //     imageStore(color_texture, pixel, original_color);
    //     return;
    // }

    // distance_through_atmosphere = min(
    //     distance_through_atmosphere,
    //     max(0.0, scene_depth - distance_to_atmosphere)
    // );

    // vec4 final_color = original_color;

    // if (distance_through_atmosphere > 0.0) {
    //     float test = distance_through_atmosphere / (atmosphere_data.radius * 2.0);
    //     float atmosphere_amount = clamp(test, 0.0, 1.0);

    //     vec3 atmosphere_color = vec3(test);
    //     final_color = vec4(mix(original_color.rgb, atmosphere_color, atmosphere_amount), original_color.a);
    // }

    // imageStore(color_texture, pixel, final_color);
}