#[compute]
#version 450
#extension GL_EXT_shader_atomic_float2 : require
#extension GL_EXT_shader_atomic_float : require

//Jad Khoury https://jadkhoury.github.io/files/MasterThesisFinal.pdf
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer restrict AtomicCounterBuffer {
    uint primitive_count_full[3];
    uint primitive_count_culled[3];
    uint primitive_count_rendered[3];
};

layout(set = 0, binding = 1, std430) buffer restrict readonly IndicesBlock {
    uint read_index;
    uint write_index;
    uint delete_index;
    uint maximum_keys;
};

layout(set = 0, binding = 2, std430) buffer restrict readonly ReadList {
    uvec4 read_list[];
};

layout(set = 0, binding = 3, std430) buffer restrict writeonly WriteFullList {
    uvec4 write_full_list[];
};

layout(set = 0, binding = 4, std430) buffer restrict writeonly WriteCullList {
    uvec4 write_cull_list[];
};

layout(set = 0, binding = 5, std430) buffer restrict readonly ExternalData {
    int low_resolution_mip_count;
    int high_resolution_mip_count;
    int tile_size;
	int lod_to_mip_map[32];

	float radius;
	int resolution;
	float height_scale;
	float sub_factor;
	uint debug_flags;

	int maximum_lod;
	int minimum_lod;

	vec2 morph_range;

	mat4 planet_transform_matrix;
	mat4 view_projection_matrix;
	vec4 camera_position_fovy;

    float height_offset;
};


layout(set = 0, binding = 6, std430) buffer restrict OutputBuffer {
    float data[];
} output_buffer;

layout(set = 0, binding = 7, std430) buffer restrict GlobalKeyData {
    uint max_lod;
    uint min_lod;
    uint stable_key_count;
    uint total_keys_per_lod[32];
};

#[include] res://Shaders/GLSL/ShaderIncludes/TesselationFunctions.inc

void set_multimesh_data(uint index, uvec4 key) {
    output_buffer.data[20 * index + 0] = 1.0;
    output_buffer.data[20 * index + 1] = 0.0;
    output_buffer.data[20 * index + 2] = 0.0;
    output_buffer.data[20 * index + 3] = 0.0;

    output_buffer.data[20 * index + 4] = 0.0;
    output_buffer.data[20 * index + 5] = 1.0;
    output_buffer.data[20 * index + 6] = 0.0;
    output_buffer.data[20 * index + 7] = 0.0;

    output_buffer.data[20 * index + 8] = 0.0;
    output_buffer.data[20 * index + 9] = 0.0;
    output_buffer.data[20 * index + 10] = 1.0;
    output_buffer.data[20 * index + 11] = 0.0;

    // Not currently using
    output_buffer.data[20 * index + 12] = 0.0;
    output_buffer.data[20 * index + 13] = 0.0;
    output_buffer.data[20 * index + 14] = 0.0;
    output_buffer.data[20 * index + 15] = 0.0;

    // Setting the key data
    output_buffer.data[20 * index + 16] = uintBitsToFloat(key.x);
    output_buffer.data[20 * index + 17] = uintBitsToFloat(key.y);
    output_buffer.data[20 * index + 18] = uintBitsToFloat(key.z);
    output_buffer.data[20 * index + 19] = uintBitsToFloat(key.w);
}
float distance_from_cam(vec3 from, mat4 planet_transform_matrix) {
    return distance(polygon_space_to_world_space(from, planet_transform_matrix), camera_position_fovy.xyz); 
}

bool triangle_in_horizon(vec3 point) {
    vec3 spherical_point = point_on_cube_to_point_on_sphere(point);

    
    float distance_from_planet = distance_from_cam(planet_transform_matrix[3].xyz, planet_transform_matrix);
    float distance_from_horizon = sqrt(pow(distance_from_planet, 2) - pow(radius, 2));
    vec3 to_planet_from_cam = planet_transform_matrix[3].xyz - camera_position_fovy.xyz;
    vec3 object_point_ignore_height = polygon_space_to_world_space(spherical_point, planet_transform_matrix);

    vec3 to_point_on_sphere_from_cam = object_point_ignore_height - camera_position_fovy.xyz;
    float angle_of_horizon = acos(distance_from_horizon / distance_from_planet);
    float angle_from_point_to_cam_to_planet = acos(dot(normalize(to_point_on_sphere_from_cam), normalize(to_planet_from_cam)));

    float bias1 = 0.5;
    bool b0 = point_in_frustum(object_point_ignore_height, view_projection_matrix, bias1); // if within view TODO look at bias
    bool b1 = (distance_from_horizon + (radius / 2.0)) >= length(to_point_on_sphere_from_cam); // if within horizon's circle
    bool b2 = angle_from_point_to_cam_to_planet <= angle_of_horizon;  // if within horizon
    if ((b0 && b1 && b2) || (b0 && b1) || (b0 && !b2))
        return true;
    return false;
}

bool triangle_in_frustum(Triangle triangle) {
    return triangle_in_horizon(triangle.v0) || triangle_in_horizon(triangle.v1) || triangle_in_horizon(triangle.v2) || triangle_in_horizon(triangle.origin);
}

void cull_key(uvec4 key, Triangle triangle, float lod) {
    bool is_culling = (debug_flags & 1u) != 0u;

    if ((is_culling && triangle_in_frustum(triangle)) || !is_culling) {
        uint write_culled_index = atomicAdd(primitive_count_culled[write_index], 1);
        write_cull_list[write_culled_index] = key;

        uint render_index = atomicAdd(primitive_count_rendered[write_index], 1);
        set_multimesh_data(render_index, key);
    }

    int key_lod = get_lod_of_key(key.xy);

    atomicAdd(total_keys_per_lod[key_lod], 1u);
    atomicMax(max_lod, uint(key_lod));
    atomicMin(min_lod, uint(key_lod));
}

uint get_junction_flags(uvec4 key, Triangle parent_triangle, float lod) {
    uint b1b2 = key.y & 0x3;
    vec3 neighbour;

    LodContext lod_context = LodContext(
        planet_transform_matrix,
        camera_position_fovy.xyz,
        sub_factor,
        radius,
        camera_position_fovy.w,
        minimum_lod,
        maximum_lod,
        height_offset
    );

    if (key.xy == uvec2(0, 1)) {
        return 4 << 29;
    }

    if ((b1b2 >> 1) == 0) { // Check parent's Y neighbour
        neighbour = parent_triangle.yNeighbor;
    }
    else if ((b1b2 >> 1) == 1) { // Check parent's X neighbour
        neighbour = parent_triangle.xNeighbor;
    }

    float neighbour_lod = polygon_space_point_to_lod(neighbour, lod_context);

    if (neighbour_lod < lod - 1) {
        return b1b2 << 29;
    }

    return 4 << 29;
}

void process_triangle(Triangle source_triangle, uvec4 source_key, Triangle parent_triangle, float lod) {
    uint write_full_index = atomicAdd(primitive_count_full[write_index], 1); 

    source_key.w |= get_junction_flags(source_key, parent_triangle, lod); 
    //TODO fix this
    // how?
    if (write_full_index >= maximum_keys)
        return;
    
    write_full_list[write_full_index] = source_key;
    cull_key(source_key, source_triangle, lod); 
}

void main() {
    uint invocationID = gl_GlobalInvocationID.x;
    if (invocationID >= primitive_count_full[read_index])
        return;

    uvec4 key = read_list[invocationID];
    key.w &= 0xFu;

    uvec4 parent_key = get_parent_key(key);
    uvec4 grand_parent_key = get_parent_key(parent_key);

    Triangle triangle = create_triangle(key);
    Triangle parent_triangle = create_triangle(parent_key);
    Triangle grand_parent_triangle = create_triangle(grand_parent_key);

    LodContext lod_context = LodContext(
        planet_transform_matrix,
        camera_position_fovy.xyz,
        sub_factor,
        radius,
        camera_position_fovy.w,
        minimum_lod,
        maximum_lod,
        height_offset
    );

    float current_LOD = get_lod_of_key(key.xy);
    float parent_target_LOD = polygon_space_point_to_lod(parent_triangle.origin, lod_context);
    float target_LOD = polygon_space_point_to_lod(triangle.origin, lod_context);

   if (target_LOD > current_LOD && current_LOD < maximum_lod) { // Subdivide 
        uvec4 children_keys[4] = get_child_keys(key); 
        for (int i = 0; i < 4; i++) { 
            Triangle child_triangle = create_triangle(children_keys[i]); 
            process_triangle(child_triangle, children_keys[i], triangle, current_LOD + 1);
        } 
    } else if (parent_target_LOD <= current_LOD - 1 && current_LOD > minimum_lod) { // Merge
        if (is_upper_left_child(key.xy)) 
            process_triangle(parent_triangle, parent_key, grand_parent_triangle, current_LOD - 1);
    } 
    else { // Keep
        process_triangle(triangle, key, parent_triangle, current_LOD);
        atomicAdd(stable_key_count, 1u);
    }
    
}
