#[compute]
#version 450
#extension GL_EXT_shader_atomic_float2 : require

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) restrict uniform image2D FeedbackTexture;

layout(set = 0, binding = 1, rgba32f) restrict uniform image2DArray IndirectionTable;

layout(set = 0, binding = 2, r32ui) restrict uniform uimage2DArray StateTable;

layout(set = 0, binding = 3, rgba32f) restrict uniform image2D ResidencyTable;

layout(std430, binding = 4) buffer restrict VirtualTextureData {
    int low_resolution_mip_count;
    int high_resolution_mip_count;

    uint grid_size;
    uint fallback_tile_offset;

    uint total_texture_slots;
    uint sqrt_total_texture_slots;

    uint request_buffer_size;
    int _padding0;
};

layout(std430, binding = 5) restrict buffer TileSlotCounter {
    uint tile_slot_counter;
};

layout(std430, set = 0, binding = 6) restrict buffer RequestBufferCounter {
    uint request_buffer_counter;
};

layout(std430, binding = 7) buffer restrict TileIDs {
    uvec4 requested_tile_ids[];
};

#[include] res://Shaders/GLSL/ShaderIncludes/VirtualTextureFunctions.inc

void main() {
    const uint PROCESSING = 0xFFFFFFFF;
    const uint NOT_PROCESSING = 0x00000000;

    ivec2 size = imageSize(FeedbackTexture);

    ivec2 invocation_id = ivec2(gl_GlobalInvocationID.xy);
    
    if (invocation_id.x >= size.x || invocation_id.y >= size.y) return;
    
    ivec4 feedback = floatBitsToInt(imageLoad(FeedbackTexture, invocation_id).rgba);
    ivec3 indirection_index = feedback.xyz;
    bool is_requesting = feedback.w == 1;

    int total_resolution_mip_count = low_resolution_mip_count + high_resolution_mip_count;
    int mip_index = indirection_index.z % int(total_resolution_mip_count);

    // Ignore entries not being requested or the request is out of bounds
    if (!is_requesting || mip_index >= 6 || mip_index < 0)
        return;

    uint results = imageAtomicCompSwap(StateTable, indirection_index, NOT_PROCESSING, PROCESSING);
    if (results == PROCESSING) return;

    uvec4 indirection_data = floatBitsToUint(imageLoad(IndirectionTable, indirection_index));

    // The tile is already loaded in the tile cache
    if (indirection_data.w != 0)
        return;

    uint request_index = atomicAdd(request_buffer_counter, 1);

    if (request_index >= request_buffer_size)
        return;

    uint tile_index = atomicAdd(tile_slot_counter, 1);
    uint usable_slots = total_texture_slots - fallback_tile_offset;
    uint slot = fallback_tile_offset + (tile_index % usable_slots);

    ivec2 residency_index = ivec2(
        slot % sqrt_total_texture_slots,
        slot / sqrt_total_texture_slots
    );

    int lod_size = 1 << mip_index;
    int mip_grid_size = int(grid_size) >> mip_index;
    int mip_step = int(grid_size) / mip_grid_size;

    uvec3 request_coords = uvec3(
        indirection_index.x / mip_step,
        indirection_index.y / mip_step,
        indirection_index.z
    );

    // Only invalidate if we actually had a previous tile
    uvec4 prev_tile_data = floatBitsToUint(imageLoad(ResidencyTable, residency_index));
    if (prev_tile_data.w != 0u) {
        int prev_mip_index = int(prev_tile_data.z % total_resolution_mip_count);
        int prev_lod_size = 1 << prev_mip_index;
        set_indirection_entry(IndirectionTable, ivec3(prev_tile_data.xyz), prev_lod_size, uvec4(0u));
    }

    requested_tile_ids[request_index] = uvec4(request_coords, slot);
    set_indirection_entry(IndirectionTable, indirection_index, lod_size, uvec4(slot, 0u, 0u, 255u));
    imageStore(ResidencyTable, residency_index, uintBitsToFloat(uvec4(indirection_index, 255u)));
}
