#[compute]
#version 450
#extension GL_EXT_shader_atomic_float2 : require

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) restrict uniform image2DArray indirectionTable;

layout(set = 0, binding = 1, r32ui) restrict uniform uimage2DArray stateTable;

layout(set = 0, binding = 2, rgba32f) restrict uniform image2D residencyTable;

layout (std430, binding = 3) buffer restrict virtual_texture_data  {
    uint grid_size;
    uint total_mips;
    uint tile_offset;
    uint total_texture_slots;

    uint request_buffer_size;
    uint requested_tile_id_counter;
    uint virtual_texture_index;
    uint _padding;
};

layout (std430, binding = 4) buffer restrict TileIDs {
    uvec4 requested_tile_ids[];
};

#[include] res://Shaders/GLSL/ShaderIncludes/VirtualTextureFunctions.inc

void main() {
    ivec3 size = imageSize(stateTable);
    ivec3 indirection_index = ivec3(gl_GlobalInvocationID.xyz);

    if (indirection_index.x >= size.x || indirection_index.y >= size.y || indirection_index.z >= size.z)
        return;

    int mip_index = indirection_index.z % int(total_mips);
    int lod_size = 1 << mip_index;

    int mip_grid_size = max(int(grid_size) >> mip_index, 1);
    int mip_step = max(int(grid_size) / mip_grid_size, 1);

    if ((indirection_index.x % mip_step) != 0 || (indirection_index.y % mip_step) != 0)
        return;

    bool is_requesting = imageLoad(stateTable, indirection_index).x != 0;
    
    // Ignore entries not being requested
    if (!is_requesting)
        return;


    uvec4 indirection_data = floatBitsToUint(imageLoad(indirectionTable, indirection_index));

    // The tile is already loaded in the tile cache
    if (indirection_data.w != 0)
        return;

    uint request_index = atomicAdd(requested_tile_id_counter, 1);

    if (request_index >= request_buffer_size)
        return;

    uint tile_index = atomicAdd(virtual_texture_index, 1);
    uint usable_slots = total_texture_slots - tile_offset;
    uint slot = tile_offset + (tile_index % usable_slots);

    ivec2 residency_index = ivec2(
        slot % grid_size,
        slot / grid_size
    );

    uvec3 request_coords = uvec3(
        indirection_index.x / mip_step,
        indirection_index.y / mip_step,
        indirection_index.z
    );


    // Only invalidate if we actually had a previous tile
    uvec4 prev_tile_data = floatBitsToUint(imageLoad(residencyTable, residency_index));
    if (prev_tile_data.w != 0u) {
        int prev_mip_index = int(prev_tile_data.z % total_mips);
        int prev_lod_size = 1 << prev_mip_index;
        set_indirection_entry(ivec3(prev_tile_data.xyz), prev_lod_size, uvec4(0u));
    }

    requested_tile_ids[request_index] = uvec4(request_coords, slot);
    set_indirection_entry(indirection_index, lod_size, uvec4(slot, 0u, 0u, 255u));
    imageStore(residencyTable, residency_index, uintBitsToFloat(uvec4(indirection_index, 255u)));
}
