using Godot;
using System;

public static class FormatConverter
{
    public static int GetBytes(Image.Format format)
    {
        return format switch
        {
            Image.Format.L8 => 1,
            Image.Format.La8 => 2,
            Image.Format.R8 => 1,
            Image.Format.Rg8 => 2,
            Image.Format.Rgb8 => 3,
            Image.Format.Rgba8 => 4,
            Image.Format.Rgba4444 => 2,
            Image.Format.Rgb565 => 2,
            Image.Format.Rf => 4,
            Image.Format.Rgf => 8,
            Image.Format.Rgbf => 12,
            Image.Format.Rgbaf => 16,
            Image.Format.Rh => 2,
            Image.Format.Rgh => 4,
            Image.Format.Rgbh => 6,
            Image.Format.Rgbah => 8,
            Image.Format.Rgbe9995 => 4,
            Image.Format.Dxt1 => 8,
            Image.Format.Dxt3 => 16,
            Image.Format.Dxt5 => 16,
            Image.Format.RgtcR => 8,
            Image.Format.RgtcRg => 16,
            Image.Format.BptcRgba => 16,
            Image.Format.BptcRgbf => 16,
            Image.Format.BptcRgbfu => 16,
            Image.Format.Etc => 8,
            Image.Format.Etc2R11 => 8,
            Image.Format.Etc2R11S => 8,
            Image.Format.Etc2Rg11 => 16,
            Image.Format.Etc2Rg11S => 16,
            Image.Format.Etc2Rgb8 => 8,
            Image.Format.Etc2Rgba8 => 16,
            Image.Format.Etc2Rgb8A1 => 8,
            Image.Format.Etc2RaAsRg => 16,
            Image.Format.Dxt5RaAsRg => 16,
            Image.Format.Astc4X4 => 16,
            Image.Format.Astc4X4Hdr => 16,
            Image.Format.Astc8X8 => 16,
            Image.Format.Astc8X8Hdr => 64,
            _ => throw new NotImplementedException($"Unknown format: {format}")
        };
    }
    public static int GetBytes(RenderingDevice.DataFormat format)
    {
        return format switch
        {
            RenderingDevice.DataFormat.R4G4UnormPack8 => 1,
            RenderingDevice.DataFormat.R4G4B4A4UnormPack16 => 2,
            RenderingDevice.DataFormat.B4G4R4A4UnormPack16 => 2,
            RenderingDevice.DataFormat.R5G6B5UnormPack16 => 2,
            RenderingDevice.DataFormat.B5G6R5UnormPack16 => 2,
            RenderingDevice.DataFormat.R5G5B5A1UnormPack16 => 2,
            RenderingDevice.DataFormat.B5G5R5A1UnormPack16 => 2,
            RenderingDevice.DataFormat.A1R5G5B5UnormPack16 => 2,
            RenderingDevice.DataFormat.R8Unorm => 1,
            RenderingDevice.DataFormat.R8Snorm => 1,
            RenderingDevice.DataFormat.R8Uscaled => 1,
            RenderingDevice.DataFormat.R8Sscaled => 1,
            RenderingDevice.DataFormat.R8Uint => 1,
            RenderingDevice.DataFormat.R8Sint => 1,
            RenderingDevice.DataFormat.R8Srgb => 1,
            RenderingDevice.DataFormat.R8G8Unorm => 2,
            RenderingDevice.DataFormat.R8G8Snorm => 2,
            RenderingDevice.DataFormat.R8G8Uscaled => 2,
            RenderingDevice.DataFormat.R8G8Sscaled => 2,
            RenderingDevice.DataFormat.R8G8Uint => 2,
            RenderingDevice.DataFormat.R8G8Sint => 2,
            RenderingDevice.DataFormat.R8G8Srgb => 2,
            RenderingDevice.DataFormat.R8G8B8Unorm => 3,
            RenderingDevice.DataFormat.R8G8B8Snorm => 3,
            RenderingDevice.DataFormat.R8G8B8Uscaled => 3,
            RenderingDevice.DataFormat.R8G8B8Sscaled => 3,
            RenderingDevice.DataFormat.R8G8B8Uint => 3,
            RenderingDevice.DataFormat.R8G8B8Sint => 3,
            RenderingDevice.DataFormat.R8G8B8Srgb => 3,
            RenderingDevice.DataFormat.B8G8R8Unorm => 3,
            RenderingDevice.DataFormat.B8G8R8Snorm => 3,
            RenderingDevice.DataFormat.B8G8R8Uscaled => 3,
            RenderingDevice.DataFormat.B8G8R8Sscaled => 3,
            RenderingDevice.DataFormat.B8G8R8Uint => 3,
            RenderingDevice.DataFormat.B8G8R8Sint => 3,
            RenderingDevice.DataFormat.B8G8R8Srgb => 3,
            RenderingDevice.DataFormat.R8G8B8A8Unorm => 4,
            RenderingDevice.DataFormat.R8G8B8A8Snorm => 4,
            RenderingDevice.DataFormat.R8G8B8A8Uscaled => 4,
            RenderingDevice.DataFormat.R8G8B8A8Sscaled => 4,
            RenderingDevice.DataFormat.R8G8B8A8Uint => 4,
            RenderingDevice.DataFormat.R8G8B8A8Sint => 4,
            RenderingDevice.DataFormat.R8G8B8A8Srgb => 4,
            RenderingDevice.DataFormat.B8G8R8A8Unorm => 4,
            RenderingDevice.DataFormat.B8G8R8A8Snorm => 4,
            RenderingDevice.DataFormat.B8G8R8A8Uscaled => 4,
            RenderingDevice.DataFormat.B8G8R8A8Sscaled => 4,
            RenderingDevice.DataFormat.B8G8R8A8Uint => 4,
            RenderingDevice.DataFormat.B8G8R8A8Sint => 4,
            RenderingDevice.DataFormat.B8G8R8A8Srgb => 4,
            RenderingDevice.DataFormat.A8B8G8R8UnormPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8SnormPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8UscaledPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8SscaledPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8UintPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8SintPack32 => 4,
            RenderingDevice.DataFormat.A8B8G8R8SrgbPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10UnormPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10SnormPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10UscaledPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10SscaledPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10UintPack32 => 4,
            RenderingDevice.DataFormat.A2R10G10B10SintPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10UnormPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10SnormPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10UscaledPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10SscaledPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10UintPack32 => 4,
            RenderingDevice.DataFormat.A2B10G10R10SintPack32 => 4,
            RenderingDevice.DataFormat.R16Unorm => 2,
            RenderingDevice.DataFormat.R16Snorm => 2,
            RenderingDevice.DataFormat.R16Uscaled => 2,
            RenderingDevice.DataFormat.R16Sscaled => 2,
            RenderingDevice.DataFormat.R16Uint => 2,
            RenderingDevice.DataFormat.R16Sint => 2,
            RenderingDevice.DataFormat.R16Sfloat => 2,
            RenderingDevice.DataFormat.R16G16Unorm => 4,
            RenderingDevice.DataFormat.R16G16Snorm => 4,
            RenderingDevice.DataFormat.R16G16Uscaled => 4,
            RenderingDevice.DataFormat.R16G16Sscaled => 4,
            RenderingDevice.DataFormat.R16G16Uint => 4,
            RenderingDevice.DataFormat.R16G16Sint => 4,
            RenderingDevice.DataFormat.R16G16Sfloat => 4,
            RenderingDevice.DataFormat.R16G16B16Unorm => 6,
            RenderingDevice.DataFormat.R16G16B16Snorm => 6,
            RenderingDevice.DataFormat.R16G16B16Uscaled => 6,
            RenderingDevice.DataFormat.R16G16B16Sscaled => 6,
            RenderingDevice.DataFormat.R16G16B16Uint => 6,
            RenderingDevice.DataFormat.R16G16B16Sint => 6,
            RenderingDevice.DataFormat.R16G16B16Sfloat => 6,
            RenderingDevice.DataFormat.R16G16B16A16Unorm => 8,
            RenderingDevice.DataFormat.R16G16B16A16Snorm => 8,
            RenderingDevice.DataFormat.R16G16B16A16Uscaled => 8,
            RenderingDevice.DataFormat.R16G16B16A16Sscaled => 8,
            RenderingDevice.DataFormat.R16G16B16A16Uint => 8,
            RenderingDevice.DataFormat.R16G16B16A16Sint => 8,
            RenderingDevice.DataFormat.R16G16B16A16Sfloat => 8,
            RenderingDevice.DataFormat.R32Uint => 4,
            RenderingDevice.DataFormat.R32Sint => 4,
            RenderingDevice.DataFormat.R32Sfloat => 4,
            RenderingDevice.DataFormat.R32G32Uint => 8,
            RenderingDevice.DataFormat.R32G32Sint => 8,
            RenderingDevice.DataFormat.R32G32Sfloat => 8,
            RenderingDevice.DataFormat.R32G32B32Uint => 12,
            RenderingDevice.DataFormat.R32G32B32Sint => 12,
            RenderingDevice.DataFormat.R32G32B32Sfloat => 12,
            RenderingDevice.DataFormat.R32G32B32A32Uint => 16,
            RenderingDevice.DataFormat.R32G32B32A32Sint => 16,
            RenderingDevice.DataFormat.R32G32B32A32Sfloat => 16,
            RenderingDevice.DataFormat.R64Uint => 8,
            RenderingDevice.DataFormat.R64Sint => 8,
            RenderingDevice.DataFormat.R64Sfloat => 8,
            RenderingDevice.DataFormat.R64G64Uint => 16,
            RenderingDevice.DataFormat.R64G64Sint => 16,
            RenderingDevice.DataFormat.R64G64Sfloat => 16,
            RenderingDevice.DataFormat.R64G64B64Uint => 24,
            RenderingDevice.DataFormat.R64G64B64Sint => 24,
            RenderingDevice.DataFormat.R64G64B64Sfloat => 24,
            RenderingDevice.DataFormat.R64G64B64A64Uint => 32,
            RenderingDevice.DataFormat.R64G64B64A64Sint => 32,
            RenderingDevice.DataFormat.R64G64B64A64Sfloat => 32,
            RenderingDevice.DataFormat.B10G11R11UfloatPack32 => 4,
            RenderingDevice.DataFormat.E5B9G9R9UfloatPack32 => 4,
            RenderingDevice.DataFormat.D16Unorm => 2,
            RenderingDevice.DataFormat.X8D24UnormPack32 => 4,
            RenderingDevice.DataFormat.D32Sfloat => 4,
            RenderingDevice.DataFormat.S8Uint => 1,
            RenderingDevice.DataFormat.D16UnormS8Uint => 4,
            RenderingDevice.DataFormat.D24UnormS8Uint => 4,
            RenderingDevice.DataFormat.D32SfloatS8Uint => 5,
            RenderingDevice.DataFormat.Bc1RgbUnormBlock => 8,
            RenderingDevice.DataFormat.Bc1RgbSrgbBlock => 8,
            RenderingDevice.DataFormat.Bc1RgbaUnormBlock => 8,
            RenderingDevice.DataFormat.Bc1RgbaSrgbBlock => 8,
            RenderingDevice.DataFormat.Bc2UnormBlock => 16,
            RenderingDevice.DataFormat.Bc2SrgbBlock => 16,
            RenderingDevice.DataFormat.Bc3UnormBlock => 16,
            RenderingDevice.DataFormat.Bc3SrgbBlock => 16,
            RenderingDevice.DataFormat.Bc4UnormBlock => 8,
            RenderingDevice.DataFormat.Bc4SnormBlock => 8,
            RenderingDevice.DataFormat.Bc5UnormBlock => 16,
            RenderingDevice.DataFormat.Bc5SnormBlock => 16,
            RenderingDevice.DataFormat.Bc6HUfloatBlock => 16,
            RenderingDevice.DataFormat.Bc6HSfloatBlock => 16,
            RenderingDevice.DataFormat.Bc7UnormBlock => 16,
            RenderingDevice.DataFormat.Bc7SrgbBlock => 16,
            RenderingDevice.DataFormat.Etc2R8G8B8UnormBlock => 8,
            RenderingDevice.DataFormat.Etc2R8G8B8SrgbBlock => 8,
            RenderingDevice.DataFormat.Etc2R8G8B8A1UnormBlock => 8,
            RenderingDevice.DataFormat.Etc2R8G8B8A1SrgbBlock => 8,
            RenderingDevice.DataFormat.Etc2R8G8B8A8UnormBlock => 16,
            RenderingDevice.DataFormat.Etc2R8G8B8A8SrgbBlock => 16,
            RenderingDevice.DataFormat.EacR11UnormBlock => 8,
            RenderingDevice.DataFormat.EacR11SnormBlock => 8,
            RenderingDevice.DataFormat.EacR11G11UnormBlock => 16,
            RenderingDevice.DataFormat.EacR11G11SnormBlock => 16,
            RenderingDevice.DataFormat.Astc4X4UnormBlock => 16,
            RenderingDevice.DataFormat.Astc4X4SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc5X4UnormBlock => 16,
            RenderingDevice.DataFormat.Astc5X4SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc5X5UnormBlock => 16,
            RenderingDevice.DataFormat.Astc5X5SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc6X5UnormBlock => 16,
            RenderingDevice.DataFormat.Astc6X5SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc6X6UnormBlock => 16,
            RenderingDevice.DataFormat.Astc6X6SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc8X5UnormBlock => 16,
            RenderingDevice.DataFormat.Astc8X5SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc8X6UnormBlock => 16,
            RenderingDevice.DataFormat.Astc8X6SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc8X8UnormBlock => 16,
            RenderingDevice.DataFormat.Astc8X8SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc10X5UnormBlock => 16,
            RenderingDevice.DataFormat.Astc10X5SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc10X6UnormBlock => 16,
            RenderingDevice.DataFormat.Astc10X6SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc10X8UnormBlock => 16,
            RenderingDevice.DataFormat.Astc10X8SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc10X10UnormBlock => 16,
            RenderingDevice.DataFormat.Astc10X10SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc12X10UnormBlock => 16,
            RenderingDevice.DataFormat.Astc12X10SrgbBlock => 16,
            RenderingDevice.DataFormat.Astc12X12UnormBlock => 16,
            RenderingDevice.DataFormat.Astc12X12SrgbBlock => 16,
            RenderingDevice.DataFormat.G8B8G8R8422Unorm => 4,
            RenderingDevice.DataFormat.B8G8R8G8422Unorm => 4,
            RenderingDevice.DataFormat.G8B8R83Plane420Unorm => 4,
            RenderingDevice.DataFormat.G8B8R82Plane420Unorm => 4,
            RenderingDevice.DataFormat.G8B8R83Plane422Unorm => 4,
            RenderingDevice.DataFormat.G8B8R82Plane422Unorm => 4,
            RenderingDevice.DataFormat.G8B8R83Plane444Unorm => 4,
            RenderingDevice.DataFormat.R10X6UnormPack16 => 2,
            RenderingDevice.DataFormat.R10X6G10X6Unorm2Pack16 => 2,
            RenderingDevice.DataFormat.R10X6G10X6B10X6A10X6Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6G10X6R10X6422Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.B10X6G10X6R10X6G10X6422Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6R10X63Plane420Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6R10X62Plane420Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6R10X63Plane422Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6R10X62Plane422Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G10X6B10X6R10X63Plane444Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.R12X4UnormPack16 => 2,
            RenderingDevice.DataFormat.R12X4G12X4Unorm2Pack16 => 2,
            RenderingDevice.DataFormat.R12X4G12X4B12X4A12X4Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4G12X4R12X4422Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.B12X4G12X4R12X4G12X4422Unorm4Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4R12X43Plane420Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4R12X42Plane420Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4R12X43Plane422Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4R12X42Plane422Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G12X4B12X4R12X43Plane444Unorm3Pack16 => 2,
            RenderingDevice.DataFormat.G16B16G16R16422Unorm => 8,
            RenderingDevice.DataFormat.B16G16R16G16422Unorm => 8,
            RenderingDevice.DataFormat.G16B16R163Plane420Unorm => 8,
            RenderingDevice.DataFormat.G16B16R162Plane420Unorm => 8,
            RenderingDevice.DataFormat.G16B16R163Plane422Unorm => 8,
            RenderingDevice.DataFormat.G16B16R162Plane422Unorm => 8,
            RenderingDevice.DataFormat.G16B16R163Plane444Unorm => 8,
            _ => throw new NotImplementedException($"Unknown format: {format}")
        };
    }

    public static RenderingDevice.DataFormat MatchDataFormat(Image.Format format)
    {
        return format switch
        {
            Image.Format.Rgba8 => RenderingDevice.DataFormat.R8G8B8A8Unorm,
            Image.Format.Rgb8 => RenderingDevice.DataFormat.R8G8B8Unorm,
            Image.Format.R8 => RenderingDevice.DataFormat.R8Unorm,
            Image.Format.L8 => RenderingDevice.DataFormat.R8Unorm,
            Image.Format.Rgbaf => RenderingDevice.DataFormat.R32G32B32A32Sfloat,
            Image.Format.Rf => RenderingDevice.DataFormat.R32Sfloat,
            _ => throw new NotImplementedException($"Unknown format: {format}")
        };
    }
    public static Image.Format MatchDataFormat(RenderingDevice.DataFormat format)
    {
        return format switch
        {
            RenderingDevice.DataFormat.R8G8B8A8Unorm => Image.Format.Rgba8,
            RenderingDevice.DataFormat.R8G8B8Unorm => Image.Format.Rgb8,
            RenderingDevice.DataFormat.R8Unorm => Image.Format.R8,
            RenderingDevice.DataFormat.R32G32B32A32Sfloat => Image.Format.Rgbaf,
            RenderingDevice.DataFormat.R32Sfloat => Image.Format.Rf,
            _ => throw new NotImplementedException($"Unknown format: {format}")
        };
    }
}